(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const money = value => `PKR ${Number(value).toLocaleString('en-PK')}`;
  const state = { orders: [], filter: 'all', query: '' };
  const statuses = ['confirmed', 'processing', 'shipped', 'completed', 'cancelled'];

  function escapeHTML(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
  function setStatus(message, kind = '') { const node = $('#adminStatus'); node.textContent = message; node.className = `admin-status ${kind}`; }
  function visibleOrders() { return state.orders.filter(({ order }) => { const statusMatch = state.filter === 'all' || order.status === state.filter; const haystack = `${order.id} ${order.customer.name} ${order.customer.email}`.toLowerCase(); return statusMatch && haystack.includes(state.query); }); }
  function renderStats() { const revenue = state.orders.reduce((sum, item) => sum + Number(item.order.total || 0), 0); const open = state.orders.filter(item => !['completed', 'cancelled'].includes(item.order.status)).length; const paid = state.orders.filter(item => ['authorized_mock', 'captured_mock'].includes(item.payment.status)).length; $('#statOrders').textContent = state.orders.length; $('#statRevenue').textContent = money(revenue); $('#statOpen').textContent = open; $('#statPaid').textContent = paid; }
  function renderTable() {
    const rows = visibleOrders();
    const body = $('#ordersBody');
    if (!rows.length) { body.innerHTML = '<tr><td colspan="7" class="table-empty">No mock orders match this filter.</td></tr>'; return; }
    body.innerHTML = rows.map(({ order, payment }) => `<tr><td><strong>${escapeHTML(order.id)}</strong><small>${new Date(order.createdAt).toLocaleString()}</small></td><td><strong>${escapeHTML(order.customer.name)}</strong><small>${escapeHTML(order.customer.email)}<br>${escapeHTML(order.customer.phone)}</small></td><td>${order.items.map(item => `<span class="order-line">${item.qty} × ${escapeHTML(item.name)}</span>`).join('')}</td><td><strong>${money(order.total)}</strong></td><td><span class="payment-pill">${escapeHTML(payment.status)}</span><small>${escapeHTML(order.paymentMethod)}</small></td><td><select class="status-select" data-id="${escapeHTML(order.id)}">${statuses.map(status => `<option value="${status}" ${status === order.status ? 'selected' : ''}>${status}</option>`).join('')}</select></td><td><button class="table-action danger" type="button" data-delete="${escapeHTML(order.id)}">Delete</button></td></tr>`).join('');
  }
  async function loadOrders() { setStatus('Checking admin session…'); try { let session; try { session = await fetch('/api/auth/me', { credentials: 'same-origin' }); } catch { throw new Error('Cannot connect to the mock server.'); } if (!session.ok) throw new Error('Please log in as an admin first.'); const sessionData = await session.json(); if (sessionData.user.role !== 'admin') throw new Error('Admin role required for this dashboard.'); setStatus('Loading…'); const response = await fetch('/api/orders', { credentials: 'same-origin' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to load orders'); state.orders = result.orders || []; renderStats(); renderTable(); setStatus(`${state.orders.length} order${state.orders.length === 1 ? '' : 's'} loaded`, 'success'); } catch (error) { setStatus(`${error.message} Start the server with node mock-server.js.`, 'error'); $('#ordersBody').innerHTML = '<tr><td colspan="7" class="table-empty">Log in with the admin account at <a href="account.html">account.html</a>, then return here.</td></tr>'; } }
  async function updateOrder(id, status) { try { const response = await fetch(`/api/orders/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Update failed'); const index = state.orders.findIndex(item => item.order.id === id); if (index >= 0) state.orders[index] = result; renderStats(); renderTable(); setStatus(`${id} marked ${status}`, 'success'); } catch (error) { setStatus(error.message, 'error'); await loadOrders(); } }
  async function deleteOrder(id) { if (!window.confirm(`Delete mock order ${id}?`)) return; try { const response = await fetch(`/api/orders/${encodeURIComponent(id)}`, { method: 'DELETE' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Delete failed'); state.orders = state.orders.filter(item => item.order.id !== id); renderStats(); renderTable(); setStatus(`${id} deleted`, 'success'); } catch (error) { setStatus(error.message, 'error'); } }
  document.addEventListener('DOMContentLoaded', () => { $('#refreshOrders').addEventListener('click', loadOrders); $('#statusFilter').addEventListener('change', event => { state.filter = event.target.value; renderTable(); }); $('#orderSearch').addEventListener('input', event => { state.query = event.target.value.trim().toLowerCase(); renderTable(); }); $('#ordersBody').addEventListener('change', event => { if (event.target.matches('.status-select')) updateOrder(event.target.dataset.id, event.target.value); }); $('#ordersBody').addEventListener('click', event => { const button = event.target.closest('[data-delete]'); if (button) deleteOrder(button.dataset.delete); }); loadOrders(); });
})();
