(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const money = value => `PKR ${Number(value).toLocaleString('en-PK')}`;
  const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
  let mode = 'login';
  const status = message => { $('#authStatus').textContent = message; };
  function setMode(next) { mode = next; $('#loginTab').classList.toggle('active', mode === 'login'); $('#registerTab').classList.toggle('active', mode === 'register'); $('#authNameGroup').hidden = mode === 'login'; $('#authSubmit').textContent = mode === 'login' ? 'Log in →' : 'Create account →'; }
  async function request(url, options = {}) { let response; try { response = await fetch(url, { ...options, credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); } catch { throw new Error('Cannot connect to the mock server. Run `node mock-server.js` and open this page at http://127.0.0.1:4173/account.html.'); } const contentType = response.headers.get('content-type') || ''; if (!contentType.includes('application/json')) throw new Error('The mock server is not handling API requests. Run `node mock-server.js` and open the site at http://127.0.0.1:4173/account.html.'); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'The mock server returned an unexpected response.'); return result; }
  function renderOrders(orders) { const container = $('#orderHistory'); if (!orders.length) { container.innerHTML = '<p class="muted">No orders yet. Your completed checkout orders will appear here.</p>'; return; } container.innerHTML = orders.map(({ order, payment }) => `<article class="history-card"><div><strong>${escapeHTML(order.id)}</strong><small>${new Date(order.createdAt).toLocaleString()}</small></div><span class="status-chip">${escapeHTML(order.status)}</span><strong>${money(order.total)}</strong><div class="history-items">${order.items.map(item => `${item.qty} × ${escapeHTML(item.name)}`).join(' · ')}</div><small>Payment: ${escapeHTML(payment.status)}</small></article>`).join(''); }
  async function loadSession() { try { const result = await request('/api/auth/me'); $('#authGuest').hidden = true; $('#authUser').hidden = false; $('#userName').textContent = result.user.name; $('#userRole').textContent = result.user.role; $('#adminLink').hidden = result.user.role !== 'admin'; $('#logoutBtn').onclick = async () => { await request('/api/auth/logout', { method: 'POST' }); window.location.reload(); }; if (result.user.role === 'customer') { const history = await request('/api/orders/mine'); renderOrders(history.orders); } else { $('#orderHistoryPanel').hidden = true; } } catch { $('#authGuest').hidden = false; $('#authUser').hidden = true; $('#adminLink').hidden = true; $('#orderHistoryPanel').hidden = true; } }
  document.addEventListener('DOMContentLoaded', () => { $('#loginTab').onclick = () => setMode('login'); $('#registerTab').onclick = () => setMode('register'); $('#authForm').onsubmit = async event => { event.preventDefault(); const data = { name: $('#authName').value.trim(), email: $('#authEmail').value.trim(), password: $('#authPassword').value }; try { const result = await request(mode === 'login' ? '/api/auth/login' : '/api/auth/register', { method: 'POST', body: JSON.stringify(data) });     status(`Welcome, ${result.user.name}.`); await loadSession(); } catch (error) { status(error.message); } }; setMode('login'); loadSession(); });
})();
