const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const PORT = Number(process.env.PORT || 4173); const ROOT = __dirname;
const orders = new Map(); const sessions = new Map();
const users = new Map([
  ['customer@example.com', { id: 'user_customer_demo', name: 'Demo Customer', email: 'customer@example.com', role: 'customer', password: 'customer123' }],
  ['admin@printora.local', { id: 'user_admin_demo', name: 'Printora Admin', email: 'admin@printora.local', role: 'admin', password: 'admin123' }]
]);
const allowedStatuses = new Set(['confirmed','processing','shipped','completed','cancelled']);
const mime = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml' };
function json(res,status,body,extra={}) { res.writeHead(status,{ 'Content-Type':mime['.json'], 'Cache-Control':'no-store', ...extra }); res.end(JSON.stringify(body)); }
function readBody(req) { return new Promise((resolve,reject)=>{ let raw=''; req.on('data',chunk=>{raw+=chunk;if(raw.length>1024*1024) reject(new Error('Request too large'));}); req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'));}catch{reject(new Error('Invalid JSON'));}}); req.on('error',reject); }); }
function cookies(req) { return Object.fromEntries((req.headers.cookie||'').split(';').map(part=>part.trim().split('=').map(decodeURIComponent)).filter(pair=>pair.length===2)); }
function currentUser(req) { const token=cookies(req).printora_session; return token ? sessions.get(token) : null; }
function setSession(res,user) { const token=crypto.randomBytes(24).toString('hex'); sessions.set(token,user); res.setHeader('Set-Cookie',`printora_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400`); }
function clearSession(res,req) { const token=cookies(req).printora_session; if(token) sessions.delete(token); res.setHeader('Set-Cookie','printora_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); }
function requireRole(req,res,role) { const user=currentUser(req); if(!user) { json(res,401,{error:'Authentication required.'}); return null; } if(role && user.role!==role) { json(res,403,{error:'You do not have permission for this resource.'}); return null; } return user; }
function validCheckout(body) { return body&&body.customer&&body.customer.name&&/[^@\s]+@[^@\s]+\.[^@\s]+/.test(body.customer.email)&&body.customer.phone&&body.customer.address&&Array.isArray(body.items)&&body.items.length&&body.items.every(item=>item.qty>0&&item.product&&Number(item.product.price)>=0); }
function makeOrder(body,user) { const id=`PR-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`; const total=body.items.reduce((sum,item)=>sum+Number(item.product.price)*Number(item.qty),0); const paymentStatus=body.paymentMethod==='cod'?'pending_cash_on_delivery':'authorized_mock'; const order={id,status:'confirmed',createdAt:new Date().toISOString(),customer:{...body.customer,userId:user?.id||null},userId:user?.id||null,items:body.items.map(item=>({id:item.id,name:item.product.name,qty:item.qty,price:Number(item.product.price)})),total,paymentMethod:body.paymentMethod||'card'}; const payment={id:`mockpay_${crypto.randomBytes(4).toString('hex')}`,status:paymentStatus,provider:'Printora Mock Payments'}; orders.set(id,{order,payment}); return {order,payment}; }
const server=http.createServer(async(req,res)=>{ const url=new URL(req.url,`http://${req.headers.host||'localhost'}`); const user=currentUser(req);
  if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});return res.end();}
  if(req.method==='POST'&&url.pathname==='/api/auth/register'){try{const body=await readBody(req);const email=String(body.email||'').trim().toLowerCase();if(!body.name||!email||!/^.{6,}$/.test(body.password||''))return json(res,400,{error:'Name, email, and a password of at least 6 characters are required.'});if(users.has(email))return json(res,409,{error:'An account with this email already exists.'});const account={id:`user_${crypto.randomBytes(5).toString('hex')}`,name:String(body.name).trim(),email,role:'customer',password:body.password};users.set(email,account);setSession(res,account);return json(res,201,{user:{id:account.id,name:account.name,email:account.email,role:account.role}});}catch(error){return json(res,400,{error:error.message});}}
  if(req.method==='POST'&&url.pathname==='/api/auth/login'){try{const body=await readBody(req);const account=users.get(String(body.email||'').trim().toLowerCase());if(!account||account.password!==body.password)return json(res,401,{error:'Invalid email or password.'});setSession(res,account);return json(res,200,{user:{id:account.id,name:account.name,email:account.email,role:account.role}});}catch(error){return json(res,400,{error:error.message});}}
  if(req.method==='POST'&&url.pathname==='/api/auth/logout'){clearSession(res,req);return json(res,200,{loggedOut:true});}
  if(req.method==='GET'&&url.pathname==='/api/auth/me'){return user?json(res,200,{user:{id:user.id,name:user.name,email:user.email,role:user.role}}):json(res,401,{error:'Not authenticated.'});}
  if(req.method==='POST'&&url.pathname==='/api/checkout'){try{const body=await readBody(req);if(!validCheckout(body))return json(res,400,{error:'Customer details and at least one valid cart item are required.'});return json(res,201,makeOrder(body,user));}catch(error){return json(res,400,{error:error.message});}}
  if(req.method==='GET'&&url.pathname==='/api/orders/mine'){const customer=requireRole(req,res,'customer');if(!customer)return;return json(res,200,{orders:[...orders.values()].filter(item=>item.order.userId===customer.id)});}
  if(req.method==='GET'&&url.pathname==='/api/orders'){if(!requireRole(req,res,'admin'))return;return json(res,200,{orders:[...orders.values()]});}
  if(url.pathname.startsWith('/api/orders/')){const id=decodeURIComponent(url.pathname.split('/').pop());const result=orders.get(id);if(!result)return json(res,404,{error:'Order not found in this mock server session.'});if(req.method==='GET'){if(!user|| (user.role!=='admin'&&result.order.userId!==user.id))return json(res,403,{error:'You do not have permission to view this order.'});return json(res,200,result);}if(req.method==='PATCH'){if(!requireRole(req,res,'admin'))return;try{const body=await readBody(req);if(!allowedStatuses.has(body.status))return json(res,400,{error:'Unsupported order status.'});result.order.status=body.status;result.order.updatedAt=new Date().toISOString();return json(res,200,result);}catch(error){return json(res,400,{error:error.message});}}if(req.method==='DELETE'){if(!requireRole(req,res,'admin'))return;orders.delete(id);return json(res,200,{deleted:true,id});}}
  if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{error:'Method not allowed'});
  let filePath=path.join(ROOT,url.pathname==='/'?'index.html':url.pathname.replace(/^\/+/,''));if(!filePath.startsWith(ROOT)||!fs.existsSync(filePath)||fs.statSync(filePath).isDirectory())filePath=path.join(ROOT,'index.html');const ext=path.extname(filePath).toLowerCase();res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});if(req.method==='HEAD')return res.end();fs.createReadStream(filePath).pipe(res);
});
server.listen(PORT,'127.0.0.1',()=>console.log(`Printora auth mock server running at http://127.0.0.1:${PORT}`));
